### ISSUE TITLE
Mistake Correction

### ISSUE THREAD

**Issue by guanhuankang** [dragonlee258079/Saliency-Ranking#2]
Thank you for the release of the codebase!

I think I found a mistake in your codebase that the structure of the dataset should be as follow:
-- dataset
   |-- Annotations
   |   |-- | train.pkl
   |   |-- | test.pkl
   |-- GT
   |   |-- train
   |   |-- | COCO_train2014_000000000110.png ...
   |   |-- test
   |   |-- | COCO_val2014_000000000192.png ...
   |-- Images
   |   |-- train
   |   |-- | COCO_train2014_000000000110.jpg ...
   |   |-- test
   |   |-- | COCO_val2014_000000000192.jpg ...

Am I correct? Thanks!

**Comment by dragonlee258079** [comment]
There are two or more objects in a single image in my dataset. And I insert the human label in my dataset and the code will extract it. I think this may cause the mistakes.

**Comment by guanhuankang** [comment]
Thank you so much!
