### ISSUE TITLE
Difference of two pre-trained models

### ISSUE THREAD

**Issue by MinglangQiao** [dragonlee258079/Saliency-Ranking#3]
Thanks for sharing the code:) I am wondering what is the difference between the pre-trained model in the "Training model" section (pre_model.pth) and the "Testing model" section (pre_model.pth). Could you give some descriptions on that ? thanks a lot

**Comment by dragonlee258079** [comment]
The pre-trained model in the "Training model" section is our modified mask R-CNN model for salient instance segmentation.
The final model in the "Testing model" section is our final model for evaluation.
