### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by cherryolg** [dragonlee258079/Saliency-Ranking#5]
Hi, I have a question that I'm a little confused about. Does the pre-trained model refer to the instance segmentation model above? Is it the model of the article "Path Aggregation Network for Instance Segmentation" or is it trained by yourself？

**Comment by nian-liu** [comment]
Does the pre-trained model refer to the instance segmentation model above? Yes.

Is it the model of the article "Path Aggregation Network for Instance Segmentation" or is it trained by yourself？
Trained by ourselves.
