### ISSUE TITLE
no model_final.pth and model_0189999.pth

### ISSUE THREAD

**Issue by sdsfdx-xgxy-ysq** [dragonlee258079/Saliency-Ranking#7]
Hello, the research direction of this paper is what I have been studying recently, which is very helpful to me. However, I encountered a problem when running your code, and I really hope to get your help. I ran the test command after configuring it according to your readme file, and the error was reported as' assertionerror: checkpoint/ checkpoint/model_ 0189999.pth not found!。’
Run the training command, and the error is as follows: 'assertionerror: checkpoint /disk2/lilong/rank_ Saliency/Pre_ Model/model_ final. pth not found!’
Do I need to train detectron2 to get these two pths? Or is it caused by my configuration error? Thank you very much.

**Comment by dragonlee258079** [comment]
Hi, the "model_final.pth", which is needed for the training command, is the pre-trained instance segmentation model [https://drive.google.com/file/d/1gyH89OVRzgvtVqyXr61y3qnGbEvwuosl/view?usp=sharing](url)

**Comment by dragonlee258079** [comment]
Hi, the "model_final.pth", which is needed for the training command, is the pre-trained instance segmentation model that refers to the "Training model" section of the readme file. It can be downloaded at the link https://drive.google.com/file/d/1gyH89OVRzgvtVqyXr61y3qnGbEvwuosl/view?usp=sharing.  The "model_0189999.pth" is our final trained model that refers to the "Testing model" section of the readme file. It can be downloaded at the link https://drive.google.com/file/d/1zBylV2C2BV_Is6yNQkNHCn4XIz27Xpr0/view?usp=sharing.

**Comment by sdsfdx-xgxy-ysq** [comment]
Thank you very much for your help!!!

**Comment by sdsfdx-xgxy-ysq** [comment]
Hello, for the 'COCO_val2014_000000000192.png' provided in your dataset. I have some problems with the relative rank order of this picture.The rank order is determined by the maximum value of the saliency map provided in the 'salicon' dataset.However, The saliency map obtained through salicon's Python API shows that the maximum value of the second instance is less than that of the third
Is it my misunderstanding? I would appreciate it if you could solve my doubts

**Comment by dragonlee258079** [comment]
I have checked the gt and density map of  'COCO_val2014_000000000192.png'
and found that the rank order of salient instances is aligned with their
density values.
[image: image.png]

sdsfdx-xgxy-ysq ***@***.***> 于2022年7月17日周日 15:47写道：
