### ISSUE TITLE
how to measure SOR metric

### ISSUE THREAD

**Issue by ruoshuichengyang** [dragonlee258079/Saliency-Ranking#8]
Hello, I have a question about how to measure SOR/SSOR  metric with your model?And I find there is no code in your project to measure SOR metric but in your paper you list SOR results, how to do this?

**Comment by dragonlee258079** [comment]
曦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dragonlee258079/Saliency-Ranking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 中午11:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dragonlee258079/Saliency-Ranking] how to measure SOR metric (Issue #8)





 
Hello, I have a question about how to measure SOR/SSOR  metric with your model?And I find there is no code in your project to measure SOR metric but in your paper you list SOR results, how to do this?
