### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by GaryHuangJL** [dragonlee258079/Saliency-Ranking#9]
Hello!Thanks for your wonderful work!But I have a question:
In the annotation file you gave for the dataset IRSR, there are 11 categories of saliency ranks from 0 to 10, however, in your paper, it seems that only 8 saliency ranks are set, how are the remaining 3 handled, or am I misunderstanding？

**Comment by dragonlee258079** [comment]
> Hello!Thanks for your wonderful work!But I have a question: In the annotation file you gave for the dataset IRSR, there are 11 categories of saliency ranks from 0 to 10, however, in your paper, it seems that only 8 saliency ranks are set, how are the remaining 3 handled, or am I misunderstanding？

We removed the annotations of objects aligned with very low saliency ranks since these objects are very rare in our dataset.

**Comment by GaryHuangJL** [comment]
Thank you! I will close the question
